### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by ikeydoherty**
Thought this might give you some breathing room if the build system just did what you told it and got out of your way, and let you work in a clean repo :)

### CODE REVIEW

**Comment by tgraven** [comment]
Thank you for fixing some of my silly mistakes, and making the resource thing actually work. That was a major pain in the butt to deal with.

**Comment by ikeydoherty** [comment]
Very welcome. Yeah I've done the resource thing various times and it can be a pain, so I always copy-paste it from my older projects now :p

**Comment by ikeydoherty** [comment]
Um I missed some dotfiles, .dirstamp and .deps, might wanna git rm -rf those, sorry

**Comment by tgraven** [comment]
It's all right, I took care of it. Thanks for notifying me.

**Pull request merged**
